### PR TITLE
Fix: first send pause request got 400

### LINKED ISSUE #7: The first pause request will get 400
### Expected Behavior
The knative service will be suspended at the beginning.

### Actual Behavior
The knative service has been running from the beginning.
And I find some logs:
```
[pod/alwayslog-00001-deployment-5cd665f859-95v5g/freeze-proxy] 2021/08/03 08:03:43 Connect to freeze daemon on: 10.128.0.30
[pod/alwayslog-00001-deployment-5cd665f859-95v5g/freeze-proxy] 2021/08/03 08:03:43 sent pause request, got 400
[pod/alwayslog-00001-deployment-5cd665f859-95v5g/freeze-proxy] 2021/08/03 08:04:43 refresh token...
[pod/alwayslog-00001-deployment-5cd665f859-95v5g/freeze-proxy] 2021/08/03 08:05:43 refresh token...
[pod/alwayslog-00001-deployment-5cd665f859-95v5g/freeze-proxy] 2021/08/03 08:06:43 refresh token...
```

### PR DESCRIPTION
**Pull request by myrat92**
when freeze proxy starts, it will immediately send a pause request,
but the token will be refreshed after a minute, so the request got 400.

# Changes

- :bug: Update the token immediately when the service starts, not after a minute

/kind <kind>

Fixes #7 

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by myrat92** [comment]
@julz

File: cmd/freezeproxy/main.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ func main() {
 	log.Println("Connect to freeze daemon on:", hostIP)
 
 	var tokenCfg Token
-	go wait.PollInfinite(time.Minute, func() (done bool, err error) {
+	go wait.PollImmediateInfinite(time.Minute, func() (done bool, err error) {
```
Comment (julz) [inline cmd/freezeproxy/main.go]: now that Im looking at this, Im wondering what the point of the PollImmediate (and now PollImmediateInfinite) is since we do a log.Fatal on any errors (which will crash the container). Wonder if we should just make this a `for {}` loop instead here?

**Review by julz — COMMENTED** [review]
hey! thanks for the PR and sorry for slow response on it

Before merging, I just want to make sure it's clear that this is a proof-of-concept/prototype repo. @psschwei is working on moving the concept upstream in to knative proper, but this repo may go away and isn't official/supported etc - very happy (and grateful) to accept PRs in the meantime, just making sure no-one is expecting this repo to stay around long term (though the equivalent feature, hopefully, should!)

File: cmd/freezeproxy/main.go (hunk 1 above)
Comment (myrat92) [reply cmd/freezeproxy/main.go]: @julz Thanks for reviewing.
The problem I had was not with the `ReadFile`.

`PollInfinite` always waits the interval before the run of 'condition'.  Here, it waits for one minute before getting token.
When freeze proxy starts, it will immediately send a pause request, but the token will be refreshed after a minute, so now the `tokenCfg` is empty and daemon will return 400.
So when the freeze-proxy get up, it need to get the token immediately instead of waiting a minute.

Comment (julz) [reply cmd/freezeproxy/main.go]: understood, but couldn't we achieve that by changing `wait.PollInfinite` in to a regular `for {}` loop rather than `PollImmediateInfinite`? i.e. something like (untested):

~~~~
go func() {
  for {
        token, err := ioutil.ReadFile("/var/run/projected/token")
 	if err != nil {
 		log.Fatal("could not read token", err)
	}
	tokenCfg.Set(string(token))
	log.Println("refresh token...")

        time.Sleep(1 * time.Minute)
  }
}()
~~~~

would be a little simpler and clearer

Comment (julz) [reply cmd/freezeproxy/main.go]: there's actually a small bug here still because with all of these approaches there's no guarantee the go routine will run the first iteration of the loop before handling a user request (since the goroutine happens in parallel to everything else). This PR makes the window much smaller, but we probably need to do an initial read of the token outside the goroutine to completely solve the bug.

Comment (myrat92) [reply cmd/freezeproxy/main.go]: Thanks for the guidance.
How about adding a wait for token is not empty before first send pause?
i.e.
```golang
	wait.PollImmediateInfinite(time.Second, func() (done bool, err error) {
		if tokenCfg.Get() != "" {
			return true, nil
		}
		return false, nil
	})
	// start paused.
	pause()
```

Or is there any other recommended way？

Comment (julz) [reply cmd/freezeproxy/main.go]: I think Id just pull the refresh in to a `refreshToken` method, and then we could just do `refreshToken(); go func() { for { time.Sleep(1 * time.Minute); refreshToken() } }()`

Comment (julz) [reply cmd/freezeproxy/main.go]: (otherwise you may have to wait up to a second for the container to start due to the polling)

Comment (myrat92) [reply cmd/freezeproxy/main.go]: I have a question, can we confirm that `refreshToken` is executed after waiting for a second?
Would it be better to use `PollImmediateInfinite` to confirm the completion of `refreshToken` execution?

Comment (julz) [reply cmd/freezeproxy/main.go]: why would you need to confirm anything if you execute it once synchronously, before the goroutine? If you wait for a second to confirm it's ready, the container might take an extra second to start up, which would be unfortunate.

Comment (myrat92) [reply cmd/freezeproxy/main.go]: I misunderstood. 

(And I am very interested in this project, what can I do for it and where can I see the progress of the moving？
Thank you very much!

Comment (myrat92) [reply cmd/freezeproxy/main.go]: @julz Thanks for your review! the PR has been updated

**Comment by julz** [comment]
thanks @Myrat92!
